### ISSUE TITLE
no IP address in cert, issues with DNS-over-TLS clients

### ISSUE THREAD

**Issue by shukryshuk** [ameshkov/legoagh#13]
![IMG_20221103_121209](https://user-images.githubusercontent.com/55014736/199646224-f9d331ba-a554-40f1-bc89-b22e74ff23a5.jpg)

how to solve this ?? i need a guide

**Comment by ameshkov** [comment]
Don't worry, you can safely ignore this warning: https://github.com/AdguardTeam/AdGuardHome/issues/4927#issuecomment-1302492786

**Comment by shukryshuk** [comment]
> Don't worry, you can safely ignore this warning: [AdguardTeam/AdGuardHome#4927 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/4927#issuecomment-1302492786)

I cant connect the dns over tls using asus router.. but im able to connect with android phone.. I found out, if I disable access setting and remove all allowed clients, im able to connect the router using dns over tls, so i assuming, this warning is related to the problem here.. do you mind helping ??

**Comment by shukryshuk** [comment]
> > Don't worry, you can safely ignore this warning: [AdguardTeam/AdGuardHome#4927 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/4927#issuecomment-1302492786)
> 
> I cant connect the dns over tls using asus router.. but im able to connect with android phone.. I found out, if I disable access setting and remove all allowed clients, im able to connect the router using dns over tls, so i assuming, this warning is related to the problem here.. do you mind helping ??

this is why I assumed this is related
![IMG_20221104_023058](https://user-images.githubusercontent.com/55014736/199805684-7b46ef16-d38e-4206-b5ef-5f3fd7a584c5.jpg)

because I need to fill in the ip address of the domain to connect to dns over tls

**Comment by ameshkov** [comment]
Nope, ASUS should work just okay.

You need to fill both the hostname and the IP address and make sure that your ASUS router trusts that certificate. As I recall it trusts let's encrypt certs just okay.

**Comment by shukryshuk** [comment]
> Nope, ASUS should work just okay.
> 
> You need to fill both the hostname and the IP address and make sure that your ASUS router trusts that certificate. As I recall it trusts let's encrypt certs just okay.

ya, its only possible to connect if i disabled allowed client in my adguard home server, and everyone can connect to my dns if I dont dissallow their ip or id. do you know why this behaviour happened ??

**Comment by ameshkov** [comment]
Well, check that you configured allowed clients properly then.

**Comment by ameshkov** [comment]
Enable verbose logging in AdGuard Home to see which clients are getting blocked and why

**Comment by shukryshuk** [comment]
> Well, check that you configured allowed clients properly then.

i configured it properly, i dont know why it wont connect. it seems asus router need to get dns from plain dns first and then it will use TLS after that.

if it uses plain dns first to connect to TLS, i need to allow my isp ip address in adguard home, but my isp dont give static ip, everytime i reboot the ip changed, so i dont know how to solve this. please help

**Comment by shukryshuk** [comment]
> > Well, check that you configured allowed clients properly then.
> 
> i configured it properly, i dont know why it wont connect. it seems asus router need to get dns from plain dns first and then it will use TLS after that.
> 
> if it uses plain dns first to connect to TLS, i need to allow my isp ip address in adguard home, but my isp dont give static ip, everytime i reboot the ip changed, so i dont know how to solve this. please help

let me explain the situation,

yes i can connect through TLS after i changed the dns without rebooting the router, but after reboot, no internet because of the dns, so i need to changed the dns back to 1.1.1.1/one.one.one.one and redo the same process after reboot, in order to connect to my adguardhome dns.

**Comment by ameshkov** [comment]
Well, it sounds as if the problem is in the router configuration. Anything useful in the router logs?

**Comment by shukryshuk** [comment]
> Well, it sounds as if the problem is in the router configuration. Anything useful in the router logs?

it cant connect to ntp server because wan is down due to dns error, the router need to connect to ntp server first to establish connection to internet. i tried solution from asus support, but not working, the only way is to change to 1.1.1.1 first and change back to my adguard home dns after the ntp synced.

**Comment by shukryshuk** [comment]
solved. after allow ALL ip from my isp in agh. thank you for your time
