### ISSUE TITLE
Option to set `--preferred-chain`

### ISSUE THREAD

**Issue by lightmaster** [ameshkov/legoagh#2]
With Let's Encrypt switching certs today, it has broken the ability for Android Private DNS to connect to AGH. Solution I've worked out is to run the lego command like this:

```
CLOUDFLARE_DNS_API_TOKEN="..." \
        ./lego \
        --dns cloudflare \
        --domains "..." \
        --domains "..." \
        --email "..." \
        run \
        --preferred-chain="ISRG Root X1"
```

Can you add an optional env variable so that if `PREFERRED-CHAIN=<something>` is set, then `--preferred-chain="<something>"` will be added after the run command?

**Comment by ameshkov** [comment]
For now, I've added an option to use ZeroSSL.

It seems that I'd better simply hardcode preferred-chain when Let's Encrypt is in use.

However, the current lego release does not support it. There were no releases since it was added in the master branch: https://github.com/go-acme/lego/pull/1227/files

**Comment by ameshkov** [comment]
Ok, nvm, `preferred-chain` should be after `run`. Weird limitation.

**Comment by lightmaster** [comment]
yea, very odd setup that I had to open an issue with their github to figure out.

**Comment by lightmaster** [comment]
I assume at some point, either Let's Encrypt will get their newer X3 chain working on Android, or Google will do something that will fix it so Private DNS works with their newer X3 chain. Checking my current script, says that X1 is valid until 2035 now and R3 is valid until 2025. I know just about nothing more about any of this, but I take that to mean that it buys at least 4 more years until its an issue again?

**Comment by ameshkov** [comment]
I am surprised that this issue even occurred since LE certs are cross-signed and all chains should've been verified. Might be a bug on the Android side.

**Comment by lightmaster** [comment]
Seems like an issue on Android's side. Lot of stuff I see online talks about manually removing the last bit of something from the cert file. Sounds like Android's Private DNS isn't handling that part very well.

Seemed like a PITA solution cuz you'd have to repeat it every month or so. Automatic bandaid sounded better.
